source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CYHPOPImageButton_Example', :exclusive => true do
  pod "CYHPOPImageButton", :path => "../"
end

target 'CYHPOPImageButton_Tests', :exclusive => true do
  pod "CYHPOPImageButton", :path => "../"

  
end
